export enum ImageMap {
  PAPER_0 = "/paper-0.jpeg",
  PAPER_1 = "/paper-1.jpeg",
  PAPER_2 = "/paper-2.jpeg",
  SIDEWALK_COPACABANA = "/sidewalk-copacabana.png",
  SIDEWALK_IPANEMA = "/sidewalk-ipanema.png",
  SIDEWALK_SAO_PAULO = "/sidewalk-sao-paulo.png",
  SKULL_0 = "/skull-0.png",
  SKULL_1 = "/skull-1.png",
  SKULL_2 = "/skull-2.png",
  TRUNK_SECTION_0 = "/trunk-section-0.jpeg",
  TRUNK_SECTION_1 = "/trunk-section-1.jpeg",
  TRUNK_SECTION_2 = "/trunk-section-2.jpeg",
  WATER_0 = "/water-0.jpeg",
  WATER_1 = "/water-1.jpeg",
  WATER_2 = "/water-2.jpeg",
}
